USE BDTRANSITO22
GO

CREATE OR ALTER PROCEDURE pa_papeletas_fechas
@FECHA1 DATE, @FECHA2 DATE
AS
	SELECT P.NROPAP, P.FECHAPAP, P.NROPLA, 
		POL.CODPOL, POL.NOMPOL, POL.PATRULLERO, 
		P.CODINF, P.FECHAPAGO
	FROM PAPELETAS P INNER JOIN POLICIAS POL
		ON P.CODPOL=POL.CODPOL
	WHERE P.FECHAPAP>=@FECHA1 and P.FECHAPAP<=@FECHA2	
GO

EXECUTE pa_papeletas_fechas '10/03/2019', '30/06/2019'
GO

CREATE OR ALTER PROCEDURE pa_papeletas_policia_anio
@CODPOL CHAR(5), @ANIO INT
AS
	SELECT P.NROPAP, P.FECHAPAP, P.NROPLA, 
		I.DESCRIP, I.IMPORTE, 
		P.CODPOL, P.FECHAPAGO
	FROM PAPELETAS P INNER JOIN INFRACCIONES I
		ON P.CODINF = I.CODINF
	WHERE P.CODPOL = @CODPOL AND
		YEAR(P.FECHAPAP) = @ANIO
GO

EXECUTE pa_papeletas_policia_anio 'P0001', 2021
GO
